# Generated by Django 4.1.3 on 2022-12-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
