# Generated by Django 4.1.3 on 2022-12-06 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EntregableDaneri', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familia',
            old_name='num',
            new_name='edad',
        ),
    ]
